blank_issues_enabled: false
contact_links:
    - name: Suggest an application
      url: https://github.com/mpesic84/winutil-app/discussions/new?category=app-suggestion
      about: If you want to suggest an application to be added, create a discussion with given template
